// Cached DOM element references
export let els = {};

export function initElements() {
  els = {
    themeToggleBtn: document.getElementById('themeToggleBtn'),
    globalThemeToggle: document.getElementById('globalThemeToggle'),
    addItemForm: document.getElementById('addItemForm'),
    generateQrBtn: document.getElementById('generateQrBtn'),
    qrCodeContainer: document.getElementById('qrCodeContainer'),
    qrScannerDialog: document.getElementById('qrScannerDialog'),
    closeQrScannerBtn: document.getElementById('closeQrScannerBtn'),
    barcodeScannerDialog: document.getElementById('barcodeScannerDialog'),
    closeBarcodeScannerBtn: document.getElementById('closeBarcodeScannerBtn'),
    scanBarcodeBtn: document.getElementById('scanBarcodeBtn'),
    showQrDialog: document.getElementById('showQrDialog'),
    showQrContainer: document.getElementById('showQrContainer'),
    closeShowQrBtn: document.getElementById('closeShowQrBtn'),
    scanProgressDialog: document.getElementById('scanProgressDialog'),
    scanProgressIcon: document.getElementById('scanProgressIcon'),
    scanProgressTitle: document.getElementById('scanProgressTitle'),
    scanProgressDesc: document.getElementById('scanProgressDesc'),
    scanProgressSpinner: document.getElementById('scanProgressSpinner'),
    scanProgressActions: document.getElementById('scanProgressActions'),
    scanRetakeBtn: document.getElementById('scanRetakeBtn'),
    scanCloseBtn: document.getElementById('scanCloseBtn'),
    addDialog: document.getElementById('addDialog'),
    fabContainer: document.querySelector('.fab-container'),
    mainFab: document.getElementById('mainFab'),
    fabMenu: document.getElementById('fabMenu'),
    fabAddManual: document.getElementById('fabAddManual'),
    fabScanQr: document.getElementById('fabScanQr'),
    fabShopMode: document.getElementById('fabShopMode'),
    closeAddDialogBtn: document.getElementById('closeAddDialogBtn'),
    searchInput: document.getElementById('searchInput'),
    statusFilter: document.getElementById('statusFilter'),
    sortSelect: document.getElementById('sortSelect'),
    itemsList: document.getElementById('itemsList'),
    itemTemplate: document.getElementById('itemTemplate'),
    loading: document.getElementById('loading'),
    stats: document.getElementById('stats'),
    statusMessage: document.getElementById('statusMessage'),
    editDialog: document.getElementById('editDialog'),
    editItemForm: document.getElementById('editItemForm'),
    cancelEditBtn: document.getElementById('cancelEditBtn'),
    editRowId: document.getElementById('editRowId'),
    editName: document.getElementById('editName'),
    editQuantity: document.getElementById('editQuantity'),
    editCategory: document.getElementById('editCategory'),
    editNotes: document.getElementById('editNotes'),
    editPrice: document.getElementById('editPrice'),
    editImage: document.getElementById('editImage'),
    metricTotal: document.getElementById('metricTotal'),
    metricDone: document.getElementById('metricDone'),
    metricLeft: document.getElementById('metricLeft'),
    metricPrice: document.getElementById('metricPrice'),
    connectionChip: document.getElementById('connectionChip'),
    connectionChipMirror: document.getElementById('connectionChipMirror'),
    syncChip: document.getElementById('syncChip'),
    navBtns: [...document.querySelectorAll('.nav-btn')],
    tabPanels: [...document.querySelectorAll('.tab-panel')],
    homeListsContainer: document.getElementById('homeListsContainer'),
    homeAddListBtn: document.getElementById('homeAddListBtn'),
    searchProductBtn: document.getElementById('searchProductBtn'),
    currentListName: document.getElementById('currentListName'),
    // Prompt dialog elements
    promptDialog: document.getElementById('promptDialog'),
    promptDialogTitle: document.getElementById('promptDialogTitle'),
    promptDialogInput: document.getElementById('promptDialogInput'),
    promptDialogCancel: document.getElementById('promptDialogCancel'),
    promptDialogOk: document.getElementById('promptDialogOk'),
    // List actions dialog elements
    listActionsDialog: document.getElementById('listActionsDialog'),
    listActionsTitle: document.getElementById('listActionsTitle'),
    listActionRename: document.getElementById('listActionRename'),
    listActionDuplicate: document.getElementById('listActionDuplicate'),
    listActionShareQr: document.getElementById('listActionShareQr'),
    listActionClear: document.getElementById('listActionClear'),
    listActionDelete: document.getElementById('listActionDelete'),
    listActionsClose: document.getElementById('listActionsClose'),
    // Categories tab elements
    categoriesList: document.getElementById('categoriesList'),
    // Filter toggle & collapse
    filterToggleBtn: document.getElementById('filterToggleBtn'),
    filtersCollapse: document.getElementById('filtersCollapse'),
    // Quick-add carousel
    quickAddSection: document.getElementById('quickAddSection'),
    quickAddCarousel: document.getElementById('quickAddCarousel'),
    quickAddTitle: document.getElementById('quickAddTitle'),
    quickAddModePersonal: document.getElementById('quickAddModePersonal'),
    quickAddModeCommon: document.getElementById('quickAddModeCommon')
  };
}
